Task2
KillerFedy/HospitalAppointment pull request #1
Opened 2022-10-10 09:26 UTC by KillerFedy

Create Repository pattern and half of UserService. Start creating Unit Tests.

2022-10-10 09:29 UTC, DeadDogDance requested changes
Мало тестов

2022-10-11 04:57 UTC, Vixorem approved these changes

2022-10-13 12:45 UTC, DeadDogDance approved these changes

2022-10-13 21:12 UTC, Vixorem approved these changes

2022-10-19 03:14 UTC, merged