Task3
KillerFedy/HospitalAppointment pull request #3
Opened 2022-10-19 07:24 UTC by KillerFedy

2022-10-20 06:25 UTC, DeadDogDance requested changes

2022-10-20 06:25 UTC, DeadDogDance commented on Domain/Interfaces/IDoctorRepository.cs
> +        public Doctor CreateDoctor(Doctor doctor);
Лучше завести отдельный класс для создания объекта, или передавать только аргументы доктора.

2022-10-20 11:30 UTC, Vixorem commented on Domain/Interfaces/IDoctorRepository.cs
> +        public Doctor CreateDoctor(Doctor doctor);
Нуу, кстати, не сказал бы
Репозиторий и так зависит от этого класса. И параметр и так содержит ровно все то, что надо репозиторию. Так что по сути можно и оставить

2022-10-20 11:31 UTC, Vixorem requested changes

2022-10-20 11:31 UTC, Vixorem commented on Domain/Interfaces/IReceptionRepository.cs
> +        public List<DateOnly> GetFreeAppointmentDateList(Specialization specialization);
А я бы сделал не дэйтонлм, потому что свободное время может быть и 8:00 и 8:30 и тд

2022-10-20 11:31 UTC, Vixorem commented on Domain/Services/ReceptionService.cs
> +            Reception reception = _receptionRepository.SaveAppointment(date);
А что если такой прием уже зарезервирован

2022-10-20 11:41 UTC, KillerFedy commented on Domain/Interfaces/IReceptionRepository.cs
> +        public List<DateOnly> GetFreeAppointmentDateList(Specialization specialization);
А как по-другому?

2022-10-20 11:42 UTC, KillerFedy commented on Domain/Services/ReceptionService.cs
> +            Reception reception = _receptionRepository.SaveAppointment(date);
Не имею представления, как по-другому сделать

2022-10-23 07:47 UTC, Vixorem commented on Domain/Entities/Reception.cs
> +        public DateOnly Date { get; private set; }
А зачем, в datetime уже есть дата

2022-10-23 07:47 UTC, Vixorem commented on Domain/Interfaces/IReceptionRepository.cs
> +        public List<DateOnly> GetFreeAppointmentDateList(Specialization specialization);
Datetime

2022-10-23 09:23 UTC, Vixorem approved these changes

2022-10-23 09:25 UTC, merged